Ensure changes introduced in 0.6.10 check the sub-command return code properly on all environments

diff --git a/src/main/bundle/bin/deploy b/src/main/bundle/bin/deploy
--- a/src/main/bundle/bin/deploy
+++ b/src/main/bundle/bin/deploy
@@ -150,13 +150,11 @@ case "$CMD" in
             # deployment configuration descriptions from https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html;
             # ensure all instances were successfully registered in the ELB, so we do not decrease the ASG size if not all instances are able to
             # handle the requests
-            set +e
-            timeout 30 ${STACK_CMD} wait-for-elb-instances ${STACK}
-            if [[ $? -ne 0 ]]; then
-                echo "ERROR CodeDeploy deployment for ${STACK} succeeded, but not all instances successfully registered in ELB. Please verify."
+            ${STACK_CMD} set-desired-capacity ${STACK} 3
+            if ! timeout 5 ${STACK_CMD} wait-for-elb-instances ${STACK}; then
+                echo -e "*\n* ERROR CodeDeploy deployment for ${STACK} succeeded, but not all instances successfully registered in ELB. Please verify. *\n*"
                 exit 1
             fi
-            set -e
 
             if ${AUTO_SCALING}; then
                 if [[ ${ORIGINAL_CAPACITY} -lt 2 ]]; then
